use_frameworks!

platform :ios, '8.0'

target 'HZSCountdownButton_Example' do
  pod 'HZSCountdownButton', :path => '../'

  target 'HZSCountdownButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
